"""initial schema

Revision ID: 2e939f8dd5d5
Revises:
Create Date: 2026-10-07 18:31:40.499336
"""

from alembic import op
import sqlalchemy as sa


revision = "2e939f8dd5d5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contracts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("file_key", sa.String(length=500), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "uploaded", "extracted", "review", "approved", "archived", name="contract_status"
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "guard_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("ALLOW", "DENY", "NEEDS_APPROVAL", name="guard_decision"),
            nullable=False,
        ),
        sa.Column("rule_ids", sa.ARRAY(sa.String(length=10)), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("approved_by", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "webhook_events",
        sa.Column("event_id", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=False),
        sa.Column("raw_json", sa.JSON(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "clauses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=50), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("quote", sa.String(length=300), nullable=False),
        sa.Column("section_ref", sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column(
            "ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "type",
            sa.Enum(
                "invoice_sent",
                "payment_received",
                "late_fee",
                "payout_sent",
                "payout_done",
                "refund",
                "dispute",
                name="ledger_type",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("ref", sa.String(length=200), nullable=True),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mandates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("approved_by", sa.String(length=200), nullable=False),
        sa.Column(
            "approved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("rules_json", sa.JSON(), nullable=False),
        sa.Column("approval_threshold", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["contract_id"],
            ["contracts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contract_id"),
    )
    op.create_table(
        "parties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column(
            "role", sa.Enum("client", "agency", "subcontractor", name="party_role"), nullable=False
        ),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("paypal_email", sa.String(length=320), nullable=True),
        sa.Column("share_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payment_terms",
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("net_days", sa.Integer(), nullable=False),
        sa.Column(
            "late_fee_type",
            sa.Enum("pct_monthly", "pct_flat", "fixed", "none", name="late_fee_type"),
            nullable=False,
        ),
        sa.Column("late_fee_value", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("grace_days", sa.Integer(), nullable=False),
        sa.Column("late_fee_cap", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("deposit_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("clause_ids", sa.ARRAY(sa.Integer()), nullable=False),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("contract_id"),
    )
    op.create_table(
        "extraction_fields",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=200), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("clause_id", sa.Integer(), nullable=True),
        sa.Column(
            "checker_verdict",
            sa.Enum("ok", "wrong", "unsupported", name="checker_verdict"),
            nullable=True,
        ),
        sa.Column("checker_reason", sa.Text(), nullable=True),
        sa.Column("user_override_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["clause_id"],
            ["clauses.id"],
        ),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "milestones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contract_id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("deliverable", sa.Text(), nullable=False),
        sa.Column("acceptance_criteria", sa.JSON(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "delivered",
                "accepted",
                "invoiced",
                "paid",
                "disputed",
                name="milestone_status",
            ),
            nullable=False,
        ),
        sa.Column("clause_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["clause_id"],
            ["clauses.id"],
        ),
        sa.ForeignKeyConstraint(["contract_id"], ["contracts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("milestone_id", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("links", sa.ARRAY(sa.Text()), nullable=False),
        sa.Column("source", sa.Enum("manual", "github", name="delivery_source"), nullable=False),
        sa.Column("acceptance_json", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["milestone_id"],
            ["milestones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("milestone_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.Enum("milestone", "late_fee", name="invoice_kind"), nullable=False),
        sa.Column("paypal_invoice_id", sa.String(length=64), nullable=True),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["milestone_id"],
            ["milestones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paypal_invoice_id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_table(
        "disputes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paypal_dispute_id", sa.String(length=64), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("evidence_pack_key", sa.String(length=500), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("paypal_dispute_id"),
    )
    op.create_table(
        "payouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("paypal_batch_id", sa.String(length=64), nullable=True),
        sa.Column("paypal_item_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("request_id", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["parties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payouts")
    op.drop_table("disputes")
    op.drop_table("invoices")
    op.drop_table("deliveries")
    op.drop_table("milestones")
    op.drop_table("extraction_fields")
    op.drop_table("payment_terms")
    op.drop_table("parties")
    op.drop_table("mandates")
    op.drop_table("ledger_entries")
    op.drop_table("clauses")
    op.drop_table("webhook_events")
    op.drop_table("guard_events")
    op.drop_table("contracts")
    # ### end Alembic commands ###
    for t in (
        "contract_status",
        "party_role",
        "milestone_status",
        "late_fee_type",
        "checker_verdict",
        "invoice_kind",
        "ledger_type",
        "guard_decision",
        "delivery_source",
    ):
        op.execute(f"DROP TYPE IF EXISTS {t}")
